name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run ktlint
        run: ./gradlew ktlint
  swiftlint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:0.50.3
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run swiftlint
        run: swiftlint --reporter github-actions-logging
        
